# see https://css-tricks.com/continuous-deployments-for-wordpress-using-github-actions/

name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Sync
      env:
        user: ftp233472-2703260
        host: foerderverein-gbv.de
        directory: /hp/ab/ah/xq/www/wordpress/wp-content/themes/wordpress-theme-libria/
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          ./ ${{env.user}}@${{env.host}}:${{env.directory}}
